name: 'Dev - Frontend Terraform Apply'

on:
  push:
    branches:
      - dev
    paths:
      - 'dev/**'
  pull_request:
    branches:
      - dev
    paths:
      - 'dev/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-22.04
    environment: development
    
    defaults:
      run:
        working-directory: ./dev

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT }}:role/oidc-inff-frontend-infrastructure
        aws-region: ap-southeast-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.5.0"

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -no-color -out=tfplan
      
    - name: Terraform Apply
      if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
      run: terraform apply -auto-approve tfplan