name: Dev - Terraform Plan
on:
 pull_request:
   branches:
     - dev
   paths:
     - 'dev/**'
     - '.github/workflows/dev-tf-plan.yml'

permissions:
 id-token: write
 contents: read
 pull-requests: write

concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true
 
jobs:
 dev_terraform_plan:
   environment:
     name: Development
   env:
     tf_version: '1.10.2'
     tf_dir: 'dev'
   runs-on: ubuntu-22.04
   defaults:
     run:
       working-directory: ./dev

   if: github.event.pull_request.state != 'approved'
   steps:
     - uses: actions/checkout@v4
     
     - uses: aws-actions/configure-aws-credentials@v2
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: ap-southeast-2

     - uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: ${{ env.tf_version }}

     - name: Terraform Plan
       id: tf_plan
       run: terraform plan -out .planfile
       env:
         TF_VAR_location: ap-southeast-2
         TF_VAR_dev_account: 376129846478

     - name: Post Terraform Plan to PR
       uses: borchero/terraform-plan-comment@v2
       with:
         working-directory: ${{ env.tf_dir }}
         token: ${{ secrets.GITHUB_TOKEN }}
         planfile: .planfile

     - name: Upload Plan to S3
       if: success()
       run: |
         aws s3 cp .planfile s3://${{ secrets.WORKFLOW_TEMP_BUCKET }}/plans/plan-${{ github.event.pull_request.number }}_${{ env.tf_dir }}
         echo "Plan uploaded to S3"