name: Test AWS Permissions

on: 
  workflow_dispatch:  # 手动触发

permissions:
  id-token: write
  contents: read

jobs:
  test_permissions:
    name: 'Test AWS Permissions'
    runs-on: ubuntu-22.04
    environment: Development

    steps:
      # 新增调试步骤：验证角色是否正确承担
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT }}:role/oidc-inff-frontend-infrastructure
          aws-region: ap-southeast-2

      - name: Debug AWS Identity
        run: |
          echo "=== 当前AWS身份信息 ==="
          aws sts get-caller-identity
          echo "=== 角色附加的策略 ==="
          aws iam list-attached-role-policies --role-name oidc-inff-frontend-infrastructure

      # 细化S3权限测试
      - name: Test S3 Bucket Permissions
        run: |
          echo "=== Testing S3 Basic Permissions ==="
          aws s3api get-bucket-acceleration --bucket dev-foundation-innovatefuture-dev-frontend-static || echo "Missing s3:GetBucketAccelerateConfiguration"
          aws s3api get-bucket-website --bucket dev-foundation-innovatefuture-dev-frontend-static || echo "Missing s3:GetBucketWebsite"
          aws s3api get-bucket-versioning --bucket dev-foundation-innovatefuture-dev-frontend-static || echo "Missing s3:GetBucketVersioning"
          aws s3api get-bucket-policy --bucket dev-foundation-innovatefuture-dev-frontend-static || echo "Missing s3:GetBucketPolicy"
          
          echo "=== Testing S3 State Bucket Access ==="
          aws s3api head-object --bucket inff-frontend-infrastructure-tfstate-melj2 --key dev/terraform.tfstate || echo "Missing s3:GetObject"
          aws s3api get-bucket-encryption --bucket inff-frontend-infrastructure-tfstate-melj2 || echo "Missing s3:GetEncryptionConfiguration"
          aws s3api list-buckets || echo "Missing s3:ListAllMyBuckets"

      # 优化CloudFront测试逻辑
      - name: Test CloudFront Permissions
        run: |
          echo "=== Testing CloudFront Permissions ==="
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query 'DistributionList.Items[0].Id' --output text) || echo "Missing cloudfront:ListDistributions"
          if [ "$DISTRIBUTION_ID" != "None" ]; then
            aws cloudfront get-distribution-config --id $DISTRIBUTION_ID || echo "Missing cloudfront:GetDistributionConfig"
          else
            echo "No CloudFront distributions found, skipping detailed checks"
          fi

      # 细化Route53测试
      - name: Test Route53 Permissions
        run: |
          echo "=== Testing Route53 Permissions ==="
          aws route53 list-hosted-zones || echo "Missing route53:ListHostedZones"
          aws route53 get-hosted-zone --id Z0802797114DVNCGZ0O39 || echo "Missing route53:GetHostedZone"
          aws route53 list-resource-record-sets --hosted-zone-id Z0802797114DVNCGZ0O39 || echo "Missing route53:ListResourceRecordSets"
          aws route53 list-tags-for-resource --resource-type hostedzone --resource-id Z0802797114DVNCGZ0O39 || echo "Missing route53:ListTagsForResource"

      # 优化ACM测试逻辑
      - name: Test ACM Permissions
        run: |
          echo "=== Testing ACM Permissions ==="
          aws acm list-certificates --region us-east-1 || echo "Missing acm:ListCertificates"
          CERT_ARN=$(aws acm list-certificates --region us-east-1 --query 'CertificateSummaryList[0].CertificateArn' --output text)
          if [ -n "$CERT_ARN" ] && [ "$CERT_ARN" != "None" ]; then
            aws acm describe-certificate --certificate-arn $CERT_ARN --region us-east-1 || echo "Missing acm:DescribeCertificate"
            aws acm list-tags-for-certificate --certificate-arn $CERT_ARN --region us-east-1 || echo "Missing acm:ListTagsForCertificate"
          else
            echo "No ACM certificates found, skipping detailed checks"
          fi

      # 新增DynamoDB细粒度测试
      - name: Test DynamoDB Permissions
        run: |
          echo "=== Testing DynamoDB Permissions ==="
          aws dynamodb describe-table --table-name inff-frontend-infrastructure-tflock || echo "Missing dynamodb:DescribeTable"
          aws dynamodb get-item --table-name inff-frontend-infrastructure-tflock --key '{"LockID": {"S": "test"}}' || echo "Missing dynamodb:GetItem"
          aws dynamodb scan --table-name inff-frontend-infrastructure-tflock --limit 1 || echo "Missing dynamodb:Scan"  # 添加limit减少负载

      # 新增IAM策略验证
      - name: Test IAM Basic Permissions
        run: |
          echo "=== Testing IAM Basic Permissions ==="
          aws iam get-role --role-name oidc-inff-frontend-infrastructure || echo "Missing iam:GetRole"
          aws iam list-role-policies --role-name oidc-inff-frontend-infrastructure || echo "Missing iam:ListRolePolicies"
