name: "Test Permissions"
on: 
  push:
    branches: ["test/permissions"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Run terraform with error logging
        run: |
          cd dev
          terraform init 2> tf_errors.log || true
          terraform plan 2>> tf_errors.log || true
      
      - name: Upload error logs
        uses: actions/upload-artifact@v3
        with:
          name: terraform-errors
          path: dev/tf_errors.log