name: Test IAM Permissions
on: workflow_dispatch

jobs:
  test_permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cd dev
          terraform init 2> error.log || true
          terraform plan 2>> error.log || true
          grep "operation error" error.log | awk -F "action" '{print $2}' | sort -u > ../missing-permissions.txt
      - uses: actions/upload-artifact@v3
        with:
          name: missing-permissions
          path: missing-permissions.txt