name: "Test Permissions"
on: 
  push:
    branches: ["test/permissions"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::376129846478:role/oidc-inff-frontend-infrastructure
          aws-region: ap-southeast-2
      
      - name: Run terraform with error logging
        run: |
          cd dev
          terraform init 2> tf_errors.log || true
          terraform plan 2>> tf_errors.log || true
      
      - uses: actions/upload-artifact@v3
        with:
          name: terraform-errors
          path: dev/tf_errors.log