name: Test IAM Permissions
on: 
  push:
    branches:
      - "test/permissions"
    paths:
      - "dev/**"

jobs:
  test_permissions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_DEV_ACCOUNT }}:role/oidc-inff-frontend-infrastructure
          aws-region: ap-southeast-2
      - run: |
          cd dev
          terraform init 2> error.log || true
          terraform plan 2>> error.log || true
          grep "operation error" error.log | awk -F "action" '{print $2}' | sort -u > ../missing-permissions.txt
      - uses: actions/upload-artifact@v3
        with:
          name: missing-permissions
          path: missing-permissions.txt
          